---
services:
  it-tools:
    image: "sharevb/it-tools:latest"
    container_name: it-tools
    restart: unless-stopped
    #ports:
    #    - "8080:8080"
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
    networks:
      - front-end
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ittools-http.entrypoints=web"
      - "traefik.http.routers.ittools-http.rule=Host(`${TOP_URL:-it-tools}.${BASE_URL:?BASE_URL not set}`)"
      - "traefik.http.routers.ittools-https.entrypoints=websecure"
      - "traefik.http.routers.ittools-https.rule=Host(`${TOP_URL:-it-tools}.${BASE_URL:?BASE_URL not set}`)"
      - "traefik.http.routers.ittools-https.tls=true"
      - "traefik.http.routers.ittools-https.tls.certresolver=production"
      - "traefik.http.routers.ittools-https.service=ittools-svc"
      - "traefik.http.services.ittools-svc.loadBalancer.server.port=8080"
      - "traefik.docker.network=front-end"
      # External magic
      - "traefik.http.routers.ittools-https-public.entrypoints=websecure-public"
      - "traefik.http.routers.ittools-https-public.rule=Host(`${TOP_URL:-it-tools}.${PUBLIC_URL:?PUBLIC_URL not set}`)"
      - "traefik.http.routers.ittools-https-public.tls=true"
      - "traefik.http.routers.ittools-https-public.tls.certresolver=production"
      - "traefik.http.routers.ittools-https-public.service=ittools-svc"

networks:
  front-end:
    external: true
