---
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    command: serve
    volumes:
      - '/docker/diun/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: America/Montreal
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: '0 0 4 * * *'
      DIUN_WATCH_JITTER: 30s
      DIUN_PROVIDERS_DOCKER: true
      DIUN_DEFAULTS_NOTIFYON: new,update
      DIUN_NOTIF_GOTIFY_ENDPOINT: $GOTIFY_URL
      DIUN_NOTIF_GOTIFY_TOKEN: $GOTIFY_TOKEN
      DIUN_NOTIF_GOTIFY_PRIORITY: 1
      DIUN_NOTIF_GOTIFY_TIMEOUT: 10s
    labels:
      - 'diun.enable=true'
    dns:
      - 1.1.1.1
      - 9.9.9.9
