services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    command: serve
    environment:
      TZ: America/Montreal
      LOG_LEVEL: info
      LOG_JSON: false
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_WATCH_JITTER: 30s
      DIUN_PROVIDERS_DOCKER: true
      DIUN_WATCH_RUNONSTARTUP: true
      DIUN_WATCH_FIRSTCHECKNOTIF: true
      DIUN_NOTIF_NTFY_ENDPOINT: $NTFY_URL
      DIUN_NOTIF_NTFY_TOPIC: diun
      DIUN_NOTIF_NTFY_TAGS: whale
      DIUN_NOTIF_NTFY_TIMEOUT: 10s
      DIUN_NOTIF_NTFY_TOKEN: $NTFY_TOKEN
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
