---

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    user: $PUID:$PGID
    container_name: vaultwarden
    # ports:
    #   - 8080:80
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
    volumes:
      - "/docker/vaultwarden/data:/data"
    networks:
      - front-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-http.entrypoints=web"
      - "traefik.http.routers.vaultwarden-http.rule=Host(`vaultwarden.local.abeaudoin.xyz`)"
      - "traefik.http.routers.vaultwarden-https.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-https.rule=Host(`vaultwarden.local.abeaudoin.xyz`)"
      - "traefik.http.routers.vaultwarden-https.tls=true"
      - "traefik.http.routers.vaultwarden-https.tls.certresolver=production"
      - "traefik.http.routers.vaultwarden-https.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadBalancer.server.port=80"

networks:
  front-end:
    external: true