---

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: "${PUID}:${PGID}" # should be owner of volumes
    # ports:
    #  - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_SPOTIFY_ID: $ND_SPOTIFY_ID
      ND_SPOTIFY_SECRET: $ND_SPOTIFY_SECRET
      ND_LASTFM_APIKEY: $ND_LASTFM_APIKEY
      ND_LASTFM_SECRET: $ND_LASTFM_SECRET
      ND_ENABLEMEDIAFILECOVERART: false
    volumes:
      - "/docker/navidrome/data:/data"
      - "/medias/music-nfs:/music:ro"
    networks:
      - front-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music-http.entrypoints=web"
      - "traefik.http.routers.music-http.rule=Host(`music.local.abeaudoin.xyz`)"
      - "traefik.http.routers.music-https.entrypoints=websecure"
      - "traefik.http.routers.music-https.rule=Host(`music.local.abeaudoin.xyz`)"
      - "traefik.http.routers.music-https.tls=true"
      - "traefik.http.routers.music-https.tls.certresolver=production"
      - "traefik.http.routers.music-https.service=music-svc"
      - "traefik.http.services.music-svc.loadBalancer.server.port=4533"
      - "traefik.docker.network=front-end"

networks:
  front-end:
    external: true