---

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      - /docker/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /docker/crowdsec/db:/var/lib/crowdsec/data/
      - /docker/crowdsec/config:/etc/crowdsec/
      - /docker/traefik/logs:/var/log/traefik/:ro
    networks:
      - front-end
    security_opt:
      - no-new-privileges:true

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    restart: unless-stopped
    environment:
      CROWDSEC_BOUNCER_API_KEY: create_a_random_api_key
      CROWDSEC_AGENT_HOST: crowdsec:8080
    networks:
      - front-end
    depends_on:
      - crowdsec
    security_opt:
      - no-new-privileges:true

networks:
  front-end:
    external: true