---

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - /docker/bind9/config:/etc/bind
      - /docker/bind9/cache:/var/cache/bind
      - /docker/bind9/records:/var/log/bind
    environment:
      - TZ
      - BIND9_USER=root