acl "trusted" {
    localhost;
    localnets;
    10.0.0.0/8;
    172.16.0.0/12;
    192.168.0.0/16;
    100.64.0.0/10;
};

options {
    directory "/var/cache/bind";

    recursion yes;
    allow-query { trusted; };

    forwarders {
        1.1.1.2;
        1.0.0.2;
    };

    dnssec-validation auto;

    listen-on port 53 { any; };
    listen-on-v6 { none; };

    allow-recursion { trusted; };
    allow-query-cache { trusted; };
};

view "local" {
    match-clients { 
        192.168.0.0/16;
        172.16.0.0/12;
    };
    recursion yes;

    zone "local.abeaudoin.xyz" {
        type master;
        file "/etc/bind/zones/db.local.abeaudoin.xyz.local";
    };
};

view "tailscale" {
    match-clients { 100.64.0.0/10; };
    recursion yes;

    zone "local.abeaudoin.xyz" {
        type master;
        file "/etc/bind/zones/db.local.abeaudoin.xyz.tailscale";
    };
};
