---
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      TZ: America/Montreal
    volumes:
      - "/docker/coredns:/etc/coredns"
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: 10m
        max-file: "3"
    labels:
      - "diun.enable=true"
