---
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    command: -conf /etc/coredns/Corefile -dns.port 53
    environment:
      TZ: America/Montreal
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - "/docker/coredns:/etc/coredns"
    labels:
      - "diun.enable=true"
