---
services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    restart: unless-stopped
    #    ports:
    #      - 3456:3456
    environment:
      TZ: America/Montreal
      # PUID: $PUID
      # PGID: $PGID
      VIKUNJA_SERVICE_PUBLICURL: $VIKUNJA_SERVICE_PUBLICURL
      VIKUNJA_DATABASE_HOST: vikunjasql
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: $VIKUNJA_DATABASE_USER
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_MIGRATION_TODOIST_ENABLE: true
      VIKUNJA_MIGRATION_TODOIST_CLIENTID: ${VIKUNJA_MIGRATION_TODOIST_CLIENTID}
      VIKUNJA_MIGRATION_TODOIST_CLIENTSECRET: ${VIKUNJA_MIGRATION_TODOIST_CLIENTSECRET}
      VIKUNJA_MIGRATION_TODOIST_REDIRECTURL: ${VIKUNJA_MIGRATION_TODOIST_REDIRECTURL}
      VIKUNJA_MAILER_ENABLED: true
      VIKUNJA_MAILER_HOST: ${VIKUNJA_MAILER_HOST}
      VIKUNJA_MAILER_PORT: ${VIKUNJA_MAILER_PORT}
      VIKUNJA_MAILER_AUTHTYPE: ${VIKUNJA_MAILER_AUTHTYPE}
      VIKUNJA_MAILER_USERNAME: ${VIKUNJA_MAILER_USERNAME}
      VIKUNJA_MAILER_PASSWORD: ${VIKUNJA_MAILER_PASSWORD}
      VIKUNJA_MAILER_FORCESSL: true
      VIKUNJA_AUTH_OPENID_ENABLED: true
      VIKUNJA_AUTH_OPENID_PROVIDERS: "AUTHENTIk"
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_NAME: ${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_NAME}
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_AUTHURL: ${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_AUTHURL}
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_CLIENTID: ${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_CLIENTID}
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_CLIENTSECRET: ${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_CLIENTSECRET}
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_LOGOUTURL: ${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIk_LOGOUTURL}
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_SCOPE: "openid email profile"
      VIKUNJA_AUTH_LOCAL_ENABLED: true
    volumes:
      - /docker/vikunja/files:/app/vikunja/files
      - /docker/vikunja/config.yml:/etc/vikunja/config.yml
    depends_on:
      vikunjasql:
        condition: service_healthy
    networks:
      - front-end
      - back-end
    dns:
      - 192.168.99.7
      - 192.168.99.8
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja-http.entrypoints=web"
      - "traefik.http.routers.vikunja-http.rule=Host(`${TOP_URL:-todo}.${BASE_URL:?BASE_URL not set}`)"
      - "traefik.http.routers.vikunja-https.entrypoints=websecure"
      - "traefik.http.routers.vikunja-https.rule=Host(`${TOP_URL:-todo}.${BASE_URL:?BASE_URL not set}`)"
      - "traefik.http.routers.vikunja-https.tls=true"
      - "traefik.http.routers.vikunja-https.tls.certresolver=production"
      - "traefik.http.routers.vikunja-https.service=vikunja-svc"
      - "traefik.http.services.vikunja-svc.loadBalancer.server.port=3456"
      - "traefik.docker.network=front-end"

  vikunjasql:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      POSTGRES_USER: vikunja
    volumes:
      - /docker/vikunja/db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s
    networks:
      - back-end
    labels:
      - "diun.enable=true"

networks:
  front-end:
    external: true
  back-end:
    external: true
