---
services:
  teamspeak:
    image: teamspeak
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TZ: America/Montreal
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: teamspeak-db
      TS3SERVER_DB_USER: ${SQL_USER:?SQL_USER not set}
      TS3SERVER_DB_PASSWORD: ${SQL_PASS:?SQL_PASS not set}
      TS3SERVER_DB_NAME: ${SQL_DB_NAME:?SQL_DB_NAME not set}
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
      teamspeak-db:
        condition: service_healthy
    networks:
      - teamspeak-internal
      - teamspeak-public
    labels:
      - "diun.enable=true"

  teamspeak-db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      TZ: America/Montreal
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS:?SQL_ROOT_PASS not set}
      MYSQL_DATABASE: ${SQL_DB_NAME:?SQL_DB_NAME not set}
      MYSQL_USER: ${SQL_USER:?SQL_USER not set}
      MYSQL_PASSWORD: ${SQL_PASS:?SQL_PASS not set}
    volumes:
      - /docker/teamspeak/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - teamspeak-internal
    labels:
      - "diun.enable=true"

networks:
  teamspeak-internal:
    internal: true
  teamspeak-public:
