---

secrets:
  cloudflare_dns_api_token:
    file: /secrets/cloudflare_dns_api_token.txt

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
      # For public Network
      - 8443:8443
    secrets:
      - cloudflare_dns_api_token
    environment:
      TZ: America/Montreal
      CLOUDFLARE_EMAIL: $CLOUDFLARE_EMAIL
      CLOUDFLARE_DNS_API_TOKEN: $CLOUDFLARE_DNS_API_TOKEN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "/docker/traefik/conf/:/etc/traefik/conf/"
      - "/docker/traefik/certs/:/etc/traefik/certs/"
    networks:
      - front-end
    env_file:
      - stack.env

networks:
  front-end:
    external: true