---

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    environment:
      TZ: America/Montreal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "/docker/traefik/conf/:/etc/traefik/conf/"
      - "/docker/traefik/certs/:/etc/traefik/certs/"
    networks:
      - front-end
    env_file:
      - stack.env

networks:
  front-end:
    external: true