---

services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    container_name: hoarder
    # ports:
    #  - 3000:3000
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: $OPENAI_API_KEY
      DATA_DIR: /data
    volumes:
      - "/docker/hoarder/data/:/data"
    env_file:
      - stack.env
    networks:
      - front-end
      - back-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoarder-https.entrypoints=websecure"
      - "traefik.http.routers.hoarder-https.rule=Host(`hoarder.local.abeaudoin.xyz`)"
      - "traefik.http.routers.hoarder-https.tls=true"
      - "traefik.http.routers.hoarder-https.tls.certresolver=production"
      - "traefik.http.routers.hoarder-https.service=hoarder-svc"
      - "traefik.http.services.hoarder-svc.loadBalancer.server.port=3000"
      - "traefik.docker.network=front-end"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    container_name: hoarder-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
    networks:
      - back-end

  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    container_name: hoarder-meilisearch
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
    env_file:
      - stack.env
    networks:
      - back-end

volumes:
  meilisearch:

networks:
  front-end:
    external: true
  back-end:
    external: true
