---
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgresdql
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
      TZ: America/Montreal
    volumes:
      - 'database:/var/lib/postgresql/data'
    env_file:
      - stack.env
    networks:
      - back-end
    labels:
      - 'diun.enable=true'

  server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2026.2.1}
    container_name: authentik-server
    restart: unless-stopped
    command: server
    shm_size: 512mb
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_DEBUG_LOG:-false}
      TZ: America/Montreal
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      # Optionally authenticate (don't add quotation marks to your password)
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS: false
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL: true
      AUTHENTIK_EMAIL__TIMEOUT: 10
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    user: $PUID:$PGID
    volumes:
      - '/docker/authentik/media:/media'
      - '/docker/authentik/custom-templates:/templates'
    env_file:
      - stack.env
    labels:
      - 'diun.enable=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.authentik-http.entrypoints=web'
      - 'traefik.http.routers.authentik-http.rule=Host(`${TOP_URL:-auth}.${BASE_URL:?base url required}`)'
      - 'traefik.http.middlewares.auth-http-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.authentik-http.middlewares=auth-http-redirect'
      - 'traefik.http.routers.authentik-https.entrypoints=websecure'
      - 'traefik.http.routers.authentik-https.rule=Host(`${TOP_URL:-auth}.${BASE_URL:?base url required}`)'
      - 'traefik.http.routers.authentik-https.tls=true'
      - 'traefik.http.routers.authentik-https.tls.certresolver=production'
      - 'traefik.http.routers.authentik-https.service=authentik-svc'
      - 'traefik.http.services.authentik-svc.loadBalancer.server.port=9000'
      - 'traefik.docker.network=front-end'
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - front-end
      - back-end

  worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2026.2.1}
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      #Add logs
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_DEBUG_LOG:-false}
      PUID: $PUID
      PGID: $PGID
      TZ: America/Montreal
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST: mail.privateemail.com
      AUTHENTIK_EMAIL__PORT: 465
      # Optionally authenticate (don't add quotation marks to your password)
      AUTHENTIK_EMAIL__USERNAME: admin@tek-sdi.com
      AUTHENTIK_EMAIL__PASSWORD: ${UTHENTIK_EMAIL__PASSWORD}
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS: false
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL: true
      AUTHENTIK_EMAIL__TIMEOUT: 10
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    user: $PUID:$PGID
    volumes:
      - '/docker/authentik/media:/media'
      - '/docker/authentik/certs:/certs'
      - '/docker/authentik/custom-templates:/templates'
    env_file:
      - stack.env
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - back-end
    labels:
      - 'diun.enable=true'

volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  front-end:
    external: true
  back-end:
    external: true
