---

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    user: $PUID:$PGID
    # ports:
    #  - 3000:3000
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
    volumes:
      - "/docker/homepage/config:/app/config"
      - "/docker/homepage/icons:/app/public/icons"
      - "/docker/homepage/images:/app/public/images"
    networks:
      - front-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-http.entrypoints=web"
      - "traefik.http.routers.homepage-http.rule=Host(`dash.abeaudoin.xyz`)"
      - "traefik.http.routers.homepage-https.entrypoints=websecure"
      - "traefik.http.routers.homepage-https.rule=Host(`dash.abeaudoin.xyz`)"
      - "traefik.http.routers.homepage-https.tls=true"
      - "traefik.http.routers.homepage-https.tls.certresolver=production"
      - "traefik.http.routers.homepage-https.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadBalancer.server.port=3000"
      - "traefik.docker.network=front-end"

networks:
  front-end:
    external: true