---

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      # - 9117:9117 # Jackett
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      # Wireguard:
      WIREGUARD_PRIVATE_KEY: $WIREGUARD_PRIVATE_KEY # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      WIREGUARD_ADDRESSES: $WIREGUARD_ADDRESSES
      # Timezone for accurate log times
      TZ: America/Montreal
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      UPDATER_PERIOD: 24h
      SERVER_COUNTRIES: $SERVER_COUNTRIES
    volumes:
      - "/docker/arr-stack/gluetun:/gluetun"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    restart: always
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
      WEBUI_PORT: 8085
    volumes:
      - "/docker/arr-stack/qbittorrent:/config"
      - "/docker/arr-stack/qbittorrent/downloads:/downloads"
    depends_on:
      - gluetun

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   restart: unless-stopped
  #   network_mode: "service:gluetun"
  #   environment:
  #     TZ: America/Montreal
  #     PUID: $PUID
  #     PGID: $PGID
  #     AUTO_UPDATE: true #optional
  #     RUN_OPTS:  #optional
  #   volumes:
  #     - "/docker/arr-stack/jackett/data:/config"
  #     - "/docker/arr-stack/jackett/blackhole:/downloads"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
    volumes:
      - "/docker/arr-stack/sonarr/data:/config"
      - "/docker/arr-stack/sonarr/tvseries:/tv" #optional
      - "/docker/arr-stack/sonarr/downloadclient-downloads:/downloads" #optional

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      TZ: America/Montreal
      PUID: $PUID
      PGID: $PGID
    volumes:
      - "/docker/arr-stack/prowlarr/data:/config"