---

services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    container_name: logseq
    restart: unless-stopped
    # ports:
    #   - 80:80
    environment:
      TZ: America/Montreal
    networks:
      - front-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logseq-https.entrypoints=websecure"
      - "traefik.http.routers.logseq-https.rule=Host(`${URL}`)"
      - "traefik.http.routers.logseq-https.tls=true"
      - "traefik.http.routers.logseq-https.tls.certresolver=production"
      - "traefik.http.routers.logseq-https.service=logseq-svc"
      - "traefik.http.services.logseq-svc.loadBalancer.server.port=80"
      - "traefik.docker.network=front-end"

networks:
  front-end:
    external: true