---

services:
  it-tools:
    image: "sharevb/it-tools:latest"
    container_name: it-tools
    restart: unless-stopped
    # ports:
    #    - '8080:8080'
    environment:
      TZ: America/Montreal
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - front-end
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: 10m
        max-file: "3"
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ittools-https.entrypoints=websecurepublic"
      - "traefik.http.routers.ittools-https.rule=Host(`${TOP_URL:-it-tools}.${PUBLIC_URL:?PUBLIC_URL not set}`)"
      - "traefik.http.routers.ittools-https.tls=true"
      - "traefik.http.routers.ittools-https.tls.certresolver=production"
      - "traefik.http.routers.ittools-https.service=ittools-svc"
      - "traefik.http.services.ittools-svc.loadBalancer.server.port=8080"
      - "traefik.docker.network=front-end"

networks:
  front-end:
    external: true
