---
services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    command: tunnel run
    environment:
      TZ: America/Montreal
      TUNNEL_TOKEN: ${TUNNEL_TOKEN:?tunnel token required}
    networks:
      - public
    labels:
      - "diun.enable=true"

networks:
  public:
    external: true
