---
services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    networks:
      - public
    labels:
      - 'diun.enable=true'

networks:
  public:
    external: true
