---

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: America/Montreal
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_CLEANUP: false
      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: ${GOTIFY_URL:?GOTIFY_URL not set}
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: ${GOTIFY_TOKEN:?GOTIFY_TOKEN not set}
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${WATCHTOWER_NOTIFICATIONS_HOSTNAME:?WATCHTOWER_NOTIFICATIONS_HOSTNAME not set}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'diun.enable=true'
