---

secrets:
  gotify_token:
    file: /secrets/watchtower_gotify_token.txt

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    secrets:
      - gotify_token
    environment:
      TZ: America/Montreal
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: $GOTIFY_URL
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: /run/secrets/gotify_token
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock